/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReferencesRouteImport } from './routes/_app/references'
import { Route as AppNewRouteImport } from './routes/_app/new'
import { Route as AppLiveRouteImport } from './routes/_app/live'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppConnectRouteImport } from './routes/_app/connect'
import { Route as AppTrackIdRouteImport } from './routes/_app/track.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReferencesRoute = AppReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackIdRoute = AppTrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof AppConnectRoute
  '/library': typeof AppLibraryRoute
  '/live': typeof AppLiveRoute
  '/new': typeof AppNewRoute
  '/references': typeof AppReferencesRoute
  '/settings': typeof AppSettingsRoute
  '/track/$id': typeof AppTrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof AppConnectRoute
  '/library': typeof AppLibraryRoute
  '/live': typeof AppLiveRoute
  '/new': typeof AppNewRoute
  '/references': typeof AppReferencesRoute
  '/settings': typeof AppSettingsRoute
  '/track/$id': typeof AppTrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/connect': typeof AppConnectRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/live': typeof AppLiveRoute
  '/_app/new': typeof AppNewRoute
  '/_app/references': typeof AppReferencesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/track/$id': typeof AppTrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/library'
    | '/live'
    | '/new'
    | '/references'
    | '/settings'
    | '/track/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/library'
    | '/live'
    | '/new'
    | '/references'
    | '/settings'
    | '/track/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/connect'
    | '/_app/library'
    | '/_app/live'
    | '/_app/new'
    | '/_app/references'
    | '/_app/settings'
    | '/_app/track/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/references': {
      id: '/_app/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof AppReferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live': {
      id: '/_app/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/track/$id': {
      id: '/_app/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof AppTrackIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConnectRoute: typeof AppConnectRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppLiveRoute: typeof AppLiveRoute
  AppNewRoute: typeof AppNewRoute
  AppReferencesRoute: typeof AppReferencesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrackIdRoute: typeof AppTrackIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectRoute: AppConnectRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppLiveRoute: AppLiveRoute,
  AppNewRoute: AppNewRoute,
  AppReferencesRoute: AppReferencesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTrackIdRoute: AppTrackIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
